### ISSUE TITLE
PROG: error: the following arguments are required: testdir

### ISSUE THREAD

**Issue by 14Letters** [ChrisJefferson/stacscheck#18]
Sorry but i've been having this trouble every time when i try to install it, can you kindly check it?

**Comment by 14Letters** [comment]
Hi, 
However it says "stacscheck: command not found”, and adding paths doesn’t really seem helpful. What should I do?
On 09/24/2019 14:55，Christopher Jefferson<notifications@github.com> wrote：

Hi!

stacscheck doesn't need "installing", once you have the program you can just run it.

If you are running some tests given to you by someone else, there should be a directory of tests provided. You need to give stacscheck that directory name. That is the "testdir", so something like:

./stacscheck /testdir/CS1234/Practical1

**Comment by ChrisJefferson** [comment]
You should always make sure the final version of your submission is checked, using stacscheck, on a lab machine. This is because that is because we will also test your submission on a machine configured like the lab machines, and it makes sure you aren't using any software, or configuration options, unique to your machine. If your code only works on your computer, and not on the lab machines, the marker will assume your code doesn't work properly. (as we, of course, while marking have no way of knowing it worked on your machine!)

Some students still like running stacscheck on their own machine while writing their code, and then make sure they check their code on our lab machine before submission.

stacscheck is a python3 script included in a single file, so can be run like any other python script would be. We don't provide explicit support in how to run stacscheck.

**Comment by 14Letters** [comment]
Really appreciate your response, i will check my work on lab machine, and many thanks.


On 09/24/2019 19:35, Christopher Jefferson wrote:

You should always make sure the final version of your submission is checked, using stacscheck, on a lab machine. This is because that is because we will also test your submission on a machine configured like the lab machines, and it makes sure you aren't using any software, or configuration options, unique to your machine. If your code only works on your computer, and not on the lab machines, the marker will assume your code doesn't work properly. (as we, of course, while marking have no way of knowing it worked on your machine!)

Some students still like running stacscheck on their own machine while writing their code, and then make sure they check their code on our lab machine before submission.

stacscheck is a python3 script included in a single file, so can be run like any other python script would be. We don't provide explicit support in how to run stacscheck.
